spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=tempdb
    username: sa
    password: dksejrrl123!@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug